{
 "title": "RED",
 "time": { "from": "now-5m", "refresh": "5s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}