{
 "title": "USE",
 "time": { "from": "now-5m", "refresh": "5s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_time_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}