name: Publish Core Image

on:
  workflow_dispatch:  # Trigger manually from GitHub Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push core image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        file: ./server/Core.Api/Dockerfile
        push: true
        tags: towk/core:latest
