name: Publish Docker Images

# Only run this workflow when triggered manually via the 'workflow_dispatch' event
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push db image
      uses: docker/build-push-action@v5
      with:
        context: ./db
        file: ./db/Dockerfile
        push: true
        tags: towk/db:latest

    - name: Build and push core image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Core.Api/Dockerfile
        push: true
        tags: towk/core:latest

    - name: Build and push dialogs image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dialogs.Api/Dockerfile
        push: true
        tags: towk/dialogs:latest
name: Publish Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push db image
      uses: docker/build-push-action@v5
      with:
        context: ./db
        file: ./db/Dockerfile
        push: true
        tags: towk/db:latest

    - name: Build and push core image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Core.Api/Dockerfile
        push: true
        tags: towk/core:latest

    - name: Build and push dialogs image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dialogs.Api/Dockerfile
        push: true
        tags: towk/dialogs:latest
